[features]
seeds = false
[programs.devnet]
gifportal = "G43hDkxT86K5KFjf4Awdsm7aJJngaR2HuB7dAP2coEZm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/hectorlobato/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
